{% set version = "0.2.1" %}

package:
  name: hydrofunctions
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hydrofunctions/hydrofunctions-{{ version }}.tar.gz
  sha256: 187a170a3154c37439a2dc9aa3df6dac1e111fbe221164ee94cd0afd4af7c032

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipython
    - matplotlib-base
    - numpy
    - pandas
    - requests

test:
  imports:
    - hydrofunctions
  requires:
    - coverage

about:
  home: https://github.com/mroberge/hydrofunctions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A suite of convenience functions for exploring water data in a Jupyter Notebook

extra:
  recipe-maintainers:
    - ocefpaf
