{% set version = "0.2.0" %}

package:
  name: hydrofunctions
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hydrofunctions/hydrofunctions-{{ version }}.tar.gz
  sha256: 0cf3f34b4ac11b538bf19451982a7c09bd9109cd81dc461016bb803309eb344d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipykernel
    - ipython
    - matplotlib-base
    - nbsphinx
    - numpy >=1.16.0
    - pandas
    - pyarrow ==0.16.0
    - requests

test:
  imports:
    - hydrofunctions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mroberge/hydrofunctions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A suite of convenience functions for exploring water data in a Jupyter Notebook

extra:
  recipe-maintainers:
    - ocefpaf
