travis:
  secure:
    BINSTAR_TOKEN: XiZxFdOhjrwZQOGsjJfsox6lL7Mox+yAz0vH4O/n7LsCiSh523tKdTI75qv0gZS4iNmo/gw2is8rEmX3Fe1stIQvyQuV9SdY2lqZyUgaPujGyViF/V7JQ7KKEg5YH+sh83XchmNTlBNWWEF+OnaVhtBEdQOtO3/jtrMgwQeIcS6dllRfvD/s9z+pqTdhW1IKEQrxSx3ZmZSaaHS2w6NruGGw95UEWWKRCc+o2eeBexN0425o5RbXyK5CJEaHEzcXtuv1w1TEO384WOa6uWGZVW+cHEv2YmWVLAbE8ojhwWE0Ogm/3Q4u3k7c3PuJuPjC+UoQoK+Fxlcz4uRknuGiaaeXPWk7e5/VwBPgEsMtQMN6gzlyo/JfPoFFW7nXH0OA9kF1hKQb1gPjwKEOaOZSNGGtcvIddfo+g1pgabEoRF2j6vpubSHyG90pnsjN85QVwA73utWTzkJKxTEOQlhUAcljfZ9IEj4CMaW32e41JgpCHUPqbeJeKf6oTxQtvg+xKT+NZIQ9lpCl3Sh6hNVYYc66RJ8wP30KqTTpyAOlaHgTRJI1h3WZ34o6ysfUqr6pB+w4kuySjHqqzi+158LSocm0rNBRWVOeBz9Ed3QPRGqjdMo1VE332TGdd9jMWpT/tYdcyLJwQhGzZJLc4tkrssboswMLl/knsKSSg6ieBfA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
